spring:
  profiles:
    active: local
logging:
  config: classpath:logback-local.xml

---

spring:
  profiles: local
  main:
    banner-mode: "off"

---

spring:
  profiles: demo
  main:
    banner-mode: "console"

