spring:
  profiles:
    active: local
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
server:
  port: 80
  servlet:
    context-path: /emrs
logging:
  config: classpath:logback-local.xml

---

spring:
  profiles: local
  main:
    banner-mode: "off"

---

spring:
  profiles: demo
  main:
    banner-mode: "console"

