spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:emrs
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2console/
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
server:
  port: 80
  servlet:
    context-path: /emrs
logging:
  config: classpath:logback-local.xml

---

spring:
  profiles: local
  main:
    banner-mode: "off"

---

spring:
  profiles: demo
  main:
    banner-mode: "console"

